version: '3'

services:
   ts-bot:
      image: danielguirra/teste:ts-bot
      container_name: ts-bot
      ports:
         - '4040:4040'
      restart: always
      command: node ./dist/src/server.js
